# Ganti 'insightmid_app' dengan nama proyek Anda
name: insightmid_app 
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Sesuaikan dengan versi SDK Anda jika perlu

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  
  # --- TAMBAHKAN INI ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11 # Untuk menemukan path penyimpanan
  fl_chart: ^0.68.0 # Untuk membuat grafik
  intl: ^0.19.0 # Untuk format tanggal
  # ---------------------
  camera: ^0.11.0 # Untuk mengakses kamera
  google_mlkit_face_detection: ^0.11.0 # Untuk deteksi wajah
  google_mlkit_commons: ^0.8.0 # Dibutuhkan oleh ML Kit
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # --- TAMBAHKAN INI ---
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  # ---------------------

flutter:
  uses-material-design: true